// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Структура одного сетевого пакета (чанка) в потоке
type BackupChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Мы используем "oneof", чтобы разделять типы пакетов внутри одного стрима.
	// Это позволяет экономить трафик и не слать имя файла в каждом пакете данных.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*BackupChunk_Metadata
	//	*BackupChunk_DataBlock
	Payload       isBackupChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_api_proto_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupChunk) GetPayload() isBackupChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackupChunk) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*BackupChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *BackupChunk) GetDataBlock() []byte {
	if x != nil {
		if x, ok := x.Payload.(*BackupChunk_DataBlock); ok {
			return x.DataBlock
		}
	}
	return nil
}

type isBackupChunk_Payload interface {
	isBackupChunk_Payload()
}

type BackupChunk_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // Шлется один раз перед началом передачи файла
}

type BackupChunk_DataBlock struct {
	DataBlock []byte `protobuf:"bytes,2,opt,name=data_block,json=dataBlock,proto3,oneof"` // Шлется многократно кусками по 64 КБ (тело файла)
}

func (*BackupChunk_Metadata) isBackupChunk_Payload() {}

func (*BackupChunk_DataBlock) isBackupChunk_Payload() {}

// Метаданные файла (аналог нашего старого бинарного заголовка)
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Абсолютный путь к файлу
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                        // Общий размер файла в байтах
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`                        // Права доступа Linux
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_api_proto_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_backup_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Ответ от сервера после завершения бэкапа
type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Успешно ли записан бэкап
	TotalFiles    int64                  `protobuf:"varint,2,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`      // Сколько файлов было обработано
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`      // Сколько байт (несжатых) получено
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Описание ошибки, если success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_api_proto_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupResponse) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *BackupResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *BackupResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_backup_proto protoreflect.FileDescriptor

const file_api_proto_backup_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/backup.proto\x12\x06backup\"m\n" +
	"\vBackupChunk\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.backup.FileMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"data_block\x18\x02 \x01(\fH\x00R\tdataBlockB\t\n" +
	"\apayload\"S\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"\x91\x01\n" +
	"\x0eBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_files\x18\x02 \x01(\x03R\n" +
	"totalFiles\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2N\n" +
	"\rBackupService\x12=\n" +
	"\fStreamBackup\x12\x13.backup.BackupChunk\x1a\x16.backup.BackupResponse(\x01B\rZ\vinternal/pbb\x06proto3"

var (
	file_api_proto_backup_proto_rawDescOnce sync.Once
	file_api_proto_backup_proto_rawDescData []byte
)

func file_api_proto_backup_proto_rawDescGZIP() []byte {
	file_api_proto_backup_proto_rawDescOnce.Do(func() {
		file_api_proto_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_backup_proto_rawDesc), len(file_api_proto_backup_proto_rawDesc)))
	})
	return file_api_proto_backup_proto_rawDescData
}

var file_api_proto_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_backup_proto_goTypes = []any{
	(*BackupChunk)(nil),    // 0: backup.BackupChunk
	(*FileMetadata)(nil),   // 1: backup.FileMetadata
	(*BackupResponse)(nil), // 2: backup.BackupResponse
}
var file_api_proto_backup_proto_depIdxs = []int32{
	1, // 0: backup.BackupChunk.metadata:type_name -> backup.FileMetadata
	0, // 1: backup.BackupService.StreamBackup:input_type -> backup.BackupChunk
	2, // 2: backup.BackupService.StreamBackup:output_type -> backup.BackupResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_backup_proto_init() }
func file_api_proto_backup_proto_init() {
	if File_api_proto_backup_proto != nil {
		return
	}
	file_api_proto_backup_proto_msgTypes[0].OneofWrappers = []any{
		(*BackupChunk_Metadata)(nil),
		(*BackupChunk_DataBlock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_backup_proto_rawDesc), len(file_api_proto_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_backup_proto_goTypes,
		DependencyIndexes: file_api_proto_backup_proto_depIdxs,
		MessageInfos:      file_api_proto_backup_proto_msgTypes,
	}.Build()
	File_api_proto_backup_proto = out.File
	file_api_proto_backup_proto_goTypes = nil
	file_api_proto_backup_proto_depIdxs = nil
}
