// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/backup.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaAgentService_StreamBackup_FullMethodName  = "/backup.MediaAgentService/StreamBackup"
	MediaAgentService_StreamRestore_FullMethodName = "/backup.MediaAgentService/StreamRestore"
)

// MediaAgentServiceClient is the client API for MediaAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Описываем службу резервного копирования
type MediaAgentServiceClient interface {
	// Метод принимает поток чанков от клиента и возвращает один финальный ответ
	StreamBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BackupChunk, BackupResponse], error)
	// Meтод для восстановления данных
	StreamRestore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreChunk], error)
}

type mediaAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaAgentServiceClient(cc grpc.ClientConnInterface) MediaAgentServiceClient {
	return &mediaAgentServiceClient{cc}
}

func (c *mediaAgentServiceClient) StreamBackup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BackupChunk, BackupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaAgentService_ServiceDesc.Streams[0], MediaAgentService_StreamBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupChunk, BackupResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAgentService_StreamBackupClient = grpc.ClientStreamingClient[BackupChunk, BackupResponse]

func (c *mediaAgentServiceClient) StreamRestore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaAgentService_ServiceDesc.Streams[1], MediaAgentService_StreamRestore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RestoreRequest, RestoreChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAgentService_StreamRestoreClient = grpc.ServerStreamingClient[RestoreChunk]

// MediaAgentServiceServer is the server API for MediaAgentService service.
// All implementations must embed UnimplementedMediaAgentServiceServer
// for forward compatibility.
//
// Описываем службу резервного копирования
type MediaAgentServiceServer interface {
	// Метод принимает поток чанков от клиента и возвращает один финальный ответ
	StreamBackup(grpc.ClientStreamingServer[BackupChunk, BackupResponse]) error
	// Meтод для восстановления данных
	StreamRestore(*RestoreRequest, grpc.ServerStreamingServer[RestoreChunk]) error
	mustEmbedUnimplementedMediaAgentServiceServer()
}

// UnimplementedMediaAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaAgentServiceServer struct{}

func (UnimplementedMediaAgentServiceServer) StreamBackup(grpc.ClientStreamingServer[BackupChunk, BackupResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamBackup not implemented")
}
func (UnimplementedMediaAgentServiceServer) StreamRestore(*RestoreRequest, grpc.ServerStreamingServer[RestoreChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamRestore not implemented")
}
func (UnimplementedMediaAgentServiceServer) mustEmbedUnimplementedMediaAgentServiceServer() {}
func (UnimplementedMediaAgentServiceServer) testEmbeddedByValue()                           {}

// UnsafeMediaAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaAgentServiceServer will
// result in compilation errors.
type UnsafeMediaAgentServiceServer interface {
	mustEmbedUnimplementedMediaAgentServiceServer()
}

func RegisterMediaAgentServiceServer(s grpc.ServiceRegistrar, srv MediaAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaAgentService_ServiceDesc, srv)
}

func _MediaAgentService_StreamBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaAgentServiceServer).StreamBackup(&grpc.GenericServerStream[BackupChunk, BackupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAgentService_StreamBackupServer = grpc.ClientStreamingServer[BackupChunk, BackupResponse]

func _MediaAgentService_StreamRestore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaAgentServiceServer).StreamRestore(m, &grpc.GenericServerStream[RestoreRequest, RestoreChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAgentService_StreamRestoreServer = grpc.ServerStreamingServer[RestoreChunk]

// MediaAgentService_ServiceDesc is the grpc.ServiceDesc for MediaAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backup.MediaAgentService",
	HandlerType: (*MediaAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBackup",
			Handler:       _MediaAgentService_StreamBackup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamRestore",
			Handler:       _MediaAgentService_StreamRestore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/backup.proto",
}
